BEGIN;

DROP TABLE IF EXISTS images, cache CASCADE;

SET TIME ZONE 'UTC';    

CREATE TABLE images (
  id SERIAL PRIMARY KEY,
  key VARCHAR(255) NOT NULL UNIQUE,
  image TEXT NOT NULL
);

CREATE TABLE cache (
  id SERIAL PRIMARY KEY,
  key VARCHAR(255) NOT NULL UNIQUE,
  image TEXT NOT NULL,
  imageId INTEGER NOT NULL,
  FOREIGN KEY (imageId) REFERENCES images(id) ON DELETE CASCADE
);

COMMIT;
